<?php

/**
 * @file
 * Theme Breakpoints for Javascript module file.
 */

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_page_attachments().
 */
function theme_breakpoints_js_page_attachments(array &$page) {
  $breakpoints = [];
  /** @var \Drupal\theme_breakpoints_js\ThemeBreakpointsJs $theme_breakpoints_js */
  $theme_breakpoints_js = \Drupal::service('theme_breakpoints_js');

  /** @var \Drupal\breakpoint\BreakpointInterface[] $theme_breakpoints */
  $theme_breakpoints = $theme_breakpoints_js->getBreakpointsForActiveTheme();

  foreach ($theme_breakpoints as $name => $definition) {
    $breakpoints[] = [
      'name' => $name,
      'mediaQuery' => $definition->getMediaQuery(),
      'multipliers' => $definition->getMultipliers(),
    ];
  }

  // Settings are needed in html head, so we cannot use
  // the default drupal settings, but have to handle them by ourself.
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'application/json',
        'data-theme-breakpoints-js' => 'theme-breakpoints-js',
      ],
      '#value' => Json::encode($breakpoints),
      '#weight' => -101,
    ],
    'theme_breakpoints_js',
  ];
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'src' => '/' . drupal_get_path('module', 'theme_breakpoints_js') . '/js/breakpointsLoader.js',
      ],
      '#weight' => -100,
    ],
    'theme_breakpoint_loader',
  ];
}
